### ISSUE TITLE
The wrong logo is packaged 

### ISSUE THREAD

**Issue by AlexGustafsson** [CourseNotesBTH/BTH-Latex-Template#1]
The build script includes the `logo.png` file in the packaged zip file. It should be `bth-logo.png`. Furthermore, there is no reason to zip a folder - the content of the folder itself should do.

Overleaf, for example, expects only files to be zipped and not a folder. Fixing this would make usage easier.

Todo:

1. Change the build script to include `bth-logo.png` and not `logo.png`
2. Change the build script to zip the files directly without a containing folder
3. Upload a new release with these changes

**Comment by maxim0x2929** [comment]
Right logo is being packed now.
New release available!
